- manifest.yml
Application set to us internal networking only
> setting app to private networking

- app/notification/models/data.py
- app/notification/models/notification.py
- app/notification/routes.py
- tests/test_route.py
More specific validation error messages were added to fix the validation bugs. Also, tests were added to check the error messages if incorrect data was posted.
> Validation bug fixed

- requirements.txt
Tiny change - Using latest of main branch in fsd_utils
> Now using latest main of fsd_utils

- app/notification/application/map_contents.py
- examplar_data/application_data.py
- requirements-dev.txt
key "form_name" renamed to "name"
> FS 1397 application confirmation bug fix

- app/notification/application/map_contents.py
- examplar_data/application_data.py
formatted time "ISO-8601" for submision date
> FS-1397-application-confirmation-email-bug-fix

- app/create_app.py
- manifest.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
Adds sentry integration using utils function
> FS-1401: add Sentry integration

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- requirements-dev.in
- requirements-dev.txt
https://digital.dclg.gov.uk/jira/browse/FS-1530
> add code analysis config and dependabot config

- app/notification/application/README.md
- app/notification/application/map_contents.py
- app/notification/model/notification.py
- app/notification/model/notifier.py
- config/envs/default.py
- openapi/api.yml
- openapi/components.yml
Notification store maps & sends incomplete application contents to govuk notify template (INCOMPLETE_APPLICATION_RECORDS)
> FS 1407 send applications on closure

- app/notification/application/map_contents.py
- app/notification/application_reminder/README.md
- app/notification/application_reminder/map_contents.py
- app/notification/magic_link/map_contents.py
- app/notification/model/notification.py
- app/notification/model/notifier.py
- config/envs/default.py
- examplar_data/application_data.py
- openapi/api.yml
- openapi/components.yml
- tests/test_application/test_application.py
- Application reminder functionality added
> FS 530 application deadline reminder

- app/notification/application/map_contents.py
- tests/test_application/test_application.py
- Datetime formatting for application submission records
> FS 1769 datetime formatting for application submission records

- requirements-dev.txt
- requirements.in
- requirements.txt
bump utils to pick up changes from communitiesuk/funding-service-design-utils#40
> FS-1855: bump utils 

- openapi/components.yml
Changes:
- `additionalProperties : true` allows us to include additional properties not defined in the yaml while validating what is there.
- Also changed the Submitted_Application to inherit from Incomplete_Application and add `date_submitted` as required. This should save some space.
> BAU : Additional properties allowed.

- examplar_data/application_data.py
- tests/test_application/test_application.py
Add test to check that the notification service can accept the full range of payloads from application store on submission
> add test and variant data

- .github/workflows/main.yml
Added environment var for the Assessment url, so that the assessment e2e test doesn't fail to run in the pipeline.
N/A
N/A
> BAU - Add env var for Assessment e2e test

- .github/workflows/main.yml
https://digital.dclg.gov.uk/jira/browse/FS-1200
Added assessment store url to enable performance tests for Assessment store.
N/A
N/A
> FS-1200: Enable performance tests for Assessment store to run in the pipelines

- .github/workflows/main.yml
Reverts communitiesuk/funding-service-design-notification#65
> Revert "FS-1200: Enable performance tests for Assessment store to run in the pipelines"

- .github/workflows/main.yml
Reverts communitiesuk/funding-service-design-notification#66
> Revert "Revert "FS-1200: Enable performance tests for Assessment store to run in the pipelines""

- app/notification/application/map_contents.py
- examplar_data/application_data.py
- tests/test_application/test_application.py
We want to convert Boolean responses to Yes/No to reflect how they appear on the application form.
N.B. I know it's weird that boolean responses are type `list` but this is how the data is represented (also used for free text answers where it will be a string value)
> FS-2310: Covert boolean reponses to yes/no

- app/notification/application/application_utils.py
- app/notification/application/map_contents.py
- app/notification/model/multi_input_data.py
- app/notification/model/notification_utils.py
This PR just adds some exceptions and logs to identify the error being caused in the test environment
and simplified some files to make it easier for debugging
> FS-2969-submit-application-returns-internal-error

- Dockerfile
- requirements-dev.in
- requirements-dev.txt
Adding debugpy to dev dependencies for use in docker runner debug
> adding debugpy for docker runner debugging

- .github/workflows/deploy.yml
- .github/workflows/package.yml
- .github/workflows/tag-to-release.yml
- Procfile
- README.md
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
https://dluhcdigital.atlassian.net/browse/FS-3205
_A brief description of the pull request_
Add paketo build and include it in the workflow
Checked container boots and begins producing output
> FS-3205 - Add paketo build and include in workflow

- .github/workflows/copilot.yml
- copilot/environments/test/manifest.yml
- copilot/frontend/manifest.yml
Adding in basic workflow 
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
Tested being run via local deployment - required manual edits to the configuration that are now being inserted via the workflow:
Notification unit tests will _not_ be a part of this PR, as they will be conducted separately after any differences between workflow and local deployment are worked through
> FS-3239: Adding basic copilot stuff

- .github/workflows/copilot.yml
https://dluhcdigital.atlassian.net/browse/FS-3082
copilot init includes deploy, so don't do it a second time
- [n/a - comment included in github workflow] README and other documentation has been updated / added (if needed)
> Don't deploy when init is set since init includes deploy

- openapi/components.yml
NOT_STARTED applications will be processed as well
> FS-3277-updated-validation-for-script-send-application-on-closure-for-cofr3w1

- .github/workflows/deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-3264
Add pre-deploy scripts separately to the AWS workflow
- [n/a] README and other documentation has been updated / added (if needed)
Ran with a `!always()` in the copilot build.
> FS-3264 split pre deploy tests

- .github/workflows/deploy.yml
- .github/workflows/tag-to-release.yml
https://dluhcdigital.atlassian.net/browse/FS-3414
Change outdated reference to fds to fsd.
- [n/a] README and other documentation has been updated / added (if needed)
> FS-3414 Amend fds to fsd

- copilot/environments/dev/manifest.yml
https://dluhcdigital.atlassian.net/browse/FS-3239
Add dev deployment to the copilot environments
- [n/a] README and other documentation has been updated / added (if needed)
> FS-3239 Add dev deployment

- copilot/environments/addons/assessment-import-queue.yml
- copilot/environments/addons/form-uploads.yml
- copilot/environments/addons/funding-service-magic-links.yml
Adding environment level, shared resources that are required by various services to the environment manifests
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3089 - adding environment addons

- config/envs/default.py
> cyp-config

- copilot/environments/addons/assessment-import-queue.yml
- copilot/environments/addons/form-uploads.yml
- copilot/environments/addons/funding-service-magic-links.yml
https://dluhcdigital.atlassian.net/browse/FS-3519
Ensure all repos have the same copilot addons as assessment so it doesn't matter where it is created from.
- [n/a] README and other documentation has been updated / added (if needed)
> FS-3519 - Bring all copilot/environments/addons directories into line

- config/envs/default.py
Adding the default email form digital planning fund
> Adding Digital Planning Fund notify email

- app/notification/model/notifier.py
- config/envs/default.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&quickFilter=344
- Added template configuration for fund DPI
- Updated configuration for template INCOMPLETE_APPLICATION_TEMPLATE_ID  for each fund as currently template for fund COF is being used for all the funds.
> FS-3562-add-dpi-configuration

- copilot/environments/addons/assessment-import-queue.yml
- copilot/environments/addons/form-uploads.yml
- copilot/environments/test/manifest.yml
* Add in CORS config for folders
+ref: FS-3623
+semver: minor
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> Update environment addons

- .github/workflows/copilot_deploy.yml
- .github/workflows/environment.yml
Updating the notification workflow to reduce repetititon
> BAU_example_workflow Updating the notification workflow to reduce repetititon

- .github/workflows/copilot_deploy.yml
- .github/workflows/environment.yml
- copilot/fsd-notification/manifest.yml
* Update config for notification manifest
* Update workflow name
+ref: BAU_example_workflow
+semver: minor
> BAU - Update workflows and manifest

- .github/workflows/copilot_deploy.yml
Redeploy if copilot changes.
_A brief description of the pull request_
> BAU deploy if copilot itself changes

- .github/workflows/copilot_deploy.yml
* Making the tagging version match with the image version referenced
+ref: FS-3718
+semver: minor
> FS-3718 Update tag version generation to be unified

- copilot/fsd-notification/manifest.yml
* Adding uat and production values to copilot config
+ref: FS-3780
+semver: minor
- [*] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3780 Updating manifest

- .github/workflows/copilot_deploy.yml
* Adding a quick check to confirm what copilot sees as an environment is what the workflow sees as the environment
+ref: FS-3780
+semver: minor
> FS-3780 Adding environment confirmation script for workflow

- .github/workflows/copilot_deploy.yml
* Previously, post deploy tests would run even if you hadn't made a change to test
* Also, uat and production would build even if dev and test passed
+ref: BAU
+semver: minor
> BAU Added workflow changes

- .github/workflows/copilot_deploy.yml
Updating the deployment jobs to be able to be read from the summary
> BAU Rename matrix jobs to be more human readable

- copilot/fsd-notification/manifest.yml
Increase CPU and memory resource allocation
> BAU Boost notification CPU and memory

- README.md
steps described on how to use the notification service
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3895
> FS-3895-update-readme-file-with-how-to-use-the-service

- app/notification/application_reminder/map_contents.py
- app/notification/model/notifier.py
- examplar_data/application_data.py
- tests/test_application/test_application.py
- tests/test_magic_link/test_magic_link.py
automation of script send_deadline_reminder:  dynamically pass the fund name, deadline date, contact help email to the Notification service
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3845
> template-contents-fix/FS-3845-send-application-reminder-script-automation

- .github/workflows/copilot_deploy.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
> BAU correct variable names

- app/notification/model/notifier.py
Provide `email_reply_to_id` param in incomplete application record
> Bau - provide `email_reply_to_id` parameter in incomplete application record

- .github/workflows/copilot_deploy.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
> BAU - Make concurrency common between deploy and test

- .pre-commit-config.yaml
- app/create_app.py
- app/notification/application/map_contents.py
- app/notification/application_reminder/map_contents.py
- app/notification/magic_link/map_contents.py
- app/notification/model/notification.py
- app/notification/model/notifier.py
- app/notification/model/response.py
- config/envs/default.py
- config/envs/unit_test.py
- examplar_data/application_data.py
- pyproject.toml
- requirements-dev.in
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- tests/test_application/test_application.py
https://dluhcdigital.atlassian.net/browse/FS-2713
- Use a single config file (`pyproject.toml`) for all the code formatters (flake8, black..)
- updated requirements
> FS-2713 single config file for all code formatters

- config/envs/default.py
Adding the correct UUIDs for the HSRA templates
> FS-4323 Adding notification UUID for HSRA

- requirements-dev.txt
- requirements.txt
bumping-up the versions
Updated the local dependencies and ran the pytest then got : 18 passed, 214 warnings in 0.55s
Deployed the changes into local docker and send a rest request to /send endpoint & email is laready in gov-notify
> bumping up new versions

- app/notification/model/notifier.py
- requirements-dev.txt
- requirements.in
- requirements.txt
Fix for some personalisation for assignment templates
> Update fields for personalisation in assignment templates

- config/envs/default.py
- config/envs/dev.py
- config/envs/test.py
- copilot/fsd-notification/manifest.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
Updating manifest and bumping utils to bring in latest config setup
> fs-4647 update manifest, bump utils

- config/envs/default.py
adding new email templates for COF25 fund
> FS-4743: adding new email templates for COF25

- config/envs/default.py
FS-4743: adding new email templates for COF25-EOI welsh
> FS-4743: adding new email templates for COF25-EOI welsh

- config/envs/default.py
1. Be on latest docker-runner and all other repos
2. Git checkout `run-dpif-r3` branch on:
- digital-form-builder-adapter
- funding-service-pre-award-stores
- funding-service-design-frontend
- funding-service-design-notification
3. `make up`
4. Annoying extra step because open date is in the future:
```
docker exec funding-service-pre-award-stores-1 python -m fund_store.scripts.amend_round_dates -q update-round-dates-fab --fund_short_name DPIF --round_short_name R3 -o PAST -d FUTURE
```
5. Go to https://frontend.levellingup.gov.localhost:3008/funding-round/DPIF/R3
> Adding DPIF-R3 config

- config/envs/default.py
Add LPDF and GBRF email config.
> Adding LPDF R1 and GBRF R1 email config
