communitiesuk/funding-service-design-notification

.github/workflows/main.yml
Comment this out so we don't block the deploy pipeline, see https://communities-govuk.slack.com/archives/C02PHBER287/p1664794101631599 for context.
=> BAU: comment out dependency on security check

.github/workflows/main.yml, manifest.yml, requirements-dev.txt, requirements.in, requirements.txt
Implements utils feature to pass through the `GITHUB_SHA` for Sentry release
- pass through github sha to app
- bump utils version
=> FS-1677: Pass through GITHUB_SHA to app 

openapi/components.yml
- The answer validation failed due to a missing answer value not counting as nullable.
=> Removed fields strict validation

.github/workflows/main.yml
Disabling e2e tests on Dev as it's giving false positives on some test runs. This is mainly due to the environment being constantly deployed per commit which disrupts the e2e test run.
Evidence that e2e application and assessment passes when running against Test env with the e2e tests not running against Dev:
https://github.com/communitiesuk/funding-service-design-frontend/actions/runs/4222595381
N/A
N/A
=> BAU - Disable e2e tests running against Dev env

.github/workflows/main.yml
Copied concurrency keys from these PRs as this repo does not use the shared workflow from the Workflows repo:
https://github.com/communitiesuk/funding-service-design-workflows/pull/43
https://github.com/communitiesuk/funding-service-design-workflows/pull/45
N/A
N/A
=> FS 2385: Copy concurrency keys from Workflow repo Notification

app/notification/application/map_contents.py, app/notification/application_reminder/map_contents.py, app/notification/magic_link/map_contents.py, app/notification/model/notifier.py, app/notification/notification_contents_base_class.py, config/envs/default.py, examplar_data/application_data.py, tests/conftest.py
https://digital.dclg.gov.uk/jira/browse/FS-2871
The Record of your application email should be displaying Night Shelter as the fund name in the Subject, Fund name, in the bottom of the email body and the reply-to email need to be made dynamic. 
During the course of this ticket, it was found that dynamic templating was not working. This has been corrected for this template and can be seen in the config files (per fund).
pytest
=> implement dynamic templates for submission

app/notification/model/__init__.py, app/notification/model/notifier.py, examplar_data/application_data.py, examplar_data/magic_link_data.py, tests/conftest.py, tests/test_application/test_application.py, tests/test_magic_link/test_magic_link.py, tests/test_routes.py, tests/test_template_types.py
Previously, the tests relied on making actual HTTP calls to test the  "/send" route, which could lead to issues in case of network issues. To enhance reliability, the " /send" route is now tested using a mocked library. This ensures a more reliable testing environment.
=> FS-2366-unit-tests-improvements

.github/workflows/copilot_deploy.yml
* Adding in paths to allow for automation - path field needs both an ignore AND an allow to function. It's not inclusive, so not adding an allow fails to fire the workflow
+ref: FS-3627
+semver: minor
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
=> FS-3627 Updating deploy scripts

.github/workflows/copilot_deploy.yml, .github/workflows/environment.yml
* Moving the id-token and content permissions to the job call, not the contents of the job
* Passing secret through to sub-job
+ref: BAU
+semver: minor
=> BAU - Move the permissions to the job call

.github/workflows/copilot_deploy.yml
Remove the no-longer-needed E2E PAT token
=> BAU Remove E2E PAT token

.github/workflows/copilot_deploy.yml
Prevent concurrency during post-deploy tests
=> FS-3797 - Block concurrency on post-deploy testing

.github/workflows/copilot_deploy.yml, copilot/fsd-notification/manifest.yml
Use prod as the environment name rather than prod.  Leave alone the configuration used by FLASK_ENV.
=> Move production to prod due to certificate name length restrictions

app/notification/application/map_contents.py, app/notification/model/notifier.py, config/envs/default.py, examplar_data/application_data.py, tests/test_application/test_application.py
- Add language concept for EOI emails, with 2 new templates for Welsh
- Translated templates added to govuk notify, ids are put in config
---
=> FS-4192: Welsh translations for EOI

requirements-dev.txt, requirements.txt
The swagger-bundle to release from 0.0.9 to 1.1.0 has been reversed.
In older versions of Connexion, this line  have been used to configure the base URL for accessing the Swagger documentation. By setting swagger_url to "/" (the root path), you would instruct Connexion to serve the Swagger documentation at the root URL of your application (usually http://localhost:5000/).
=>  reverse dependabot-pip-swagger-ui-bundle-1.1.0

copilot/fsd-notification/manifest.yml
FS-4411: Overprovision instance
##Change description
Reduce the number of instance to 1 in Dev and change the ECS launch_type to Fargate-spot.
Unit tests and other appropriate tests added or updated
README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
_Will check after deployment by logging into the ECS console and view the service and instance configuration
Screenshots of UI changes (if applicable)
=> FS-4411:Over-provision instance and change to Fargate-spot

config/envs/default.py, config/envs/unit_test.py, examplar_data/application_data.py, examplar_data/magic_link_data.py, openapi/api.yml
The old COF support email was using the levellingup domain ( [cof@levellingup.gov.uk](mailto:cof@levellingup.gov.uk) ). This has been updated to the communities domain ( [cof@communities.gov.uk](mailto:cof@communities.gov.uk) )
=> Update COF support email to communities from levellingup

app/notification/model/notifier.py, config/envs/default.py, examplar_data/application_data.py, tests/test_application/test_application.py
https://mhclgdigital.atlassian.net/browse/FS-3850
- New notify template created APPLICATION_RECORD_OF_SUBMISSION (Welsh) for application submitted in Welsh
- Changes made to use template based on language set in the application
- Select Welsh language, create a new COF application, complete and submit the application, validate that the email sent to the user upon submission is in Welsh and contains correct Welsh translations
=> FS-3850: Application submit email template for Welsh

app/notification/model/notification.py, app/notification/model/notifier.py, config/envs/default.py
Here added try catch to handle errors while calling the gov notify and logging & raising a an error also added same structure for  APPLICATION_RECORD_TEMPLATE_ID and now when submitted an application it will use the given language or by default it will get en
=> Adding notification related logs and adding same structure for all the funds for few email templates 

config/envs/development.py
Changing the development log level to info so that the logs for docker runner stop constantly scrolling
=> changing local log level to info

copilot/fsd-notification/manifest.yml
This is because the `recreate` deployment method leads to downtime, which can cause tests to flake. It is not any faster than a normal deployment, and causes tests to break. I am not sure why it was chosen to begin with.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling
=> Turn off recreate deploys in test environment

app/notification/model/notification.py, app/notification/model/notifier.py, examplar_data/application_data.py, examplar_data/magic_link_data.py, tests/test_application/test_application.py
https://mhclgdigital.atlassian.net/browse/FSPT-137
Our end-to-end test suite is currently taking quite a long time to run, as many of the tests run sequentially. The main reason for needing them to run sequentially is that some tests login as the same user, and the login attempts are in conflict. This conflict is not handled well by the end-to-end tests and concurrent logins are not well supported by authenticator. Authenticator allows multiple login sessions to exist at once, but does not allow multiple unredeemed magic links to exist for one account at the same time. Furthermore, the end-to-end tests use a "list all magic links" endpoint on authenticator and then grab the top magic link off the stack. This link isn't necessarily associated with the account that they are trying to log in …
=> Allow assigning our own reference to Notify emails

pyproject.toml, uv.lock
This is to pull in the ability to disable the config table from https://github.com/communitiesuk/funding-service-design-utils/pull/169.
v6 added a breaking change, but it was reverted in 6.0.1 so nothing to do.
=> Bump fsd-utils
